homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation_home
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone_home


# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Custom UI Panels
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:floor-plan
    url_path: floorplan
    config: !include config/floorplan.yaml
    
# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
#Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:


#Amazon Alexa
emulated_hue:
  listen_port: 80


telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api
    allowed_chat_ids:
      - !secret telegram_bot_chat_ID 

notify:
  - name: hass_telegram
    platform: telegram
    chat_id: !secret telegram_bot_chat_ID

#python_script:
# Weather prediction
#sensor:
# - platform: yr
#weather:
#  - platform: yweather
#    name: Weather
#    woeid: !secret yahoo_woeid

#google_assistant:
  #project_id: hass
  #client_id: !secret assistant_client_id
  #access_token: !secret assistant_access_token
  #agent_user_id: !secret assistant_user_id 
  #api_key: !secret assistant_access_api
  #exposed_domains:
    #- switch
    #- light
    #- group

#myqtt:


# Text to speech
tts:
  - platform: google

####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################

automation: !include_dir_merge_list automation
zone: !include zones.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
device_tracker: !include device_tracker.yaml
light: !include lights.yaml
script: !include scripts.yaml
group: !include groups.yaml

#camera: !include camera.yaml
#history: !include history.yaml
#logbook: !include logbook.yaml
#logger: !include logger.yaml
#mqtt: !include mqtt.yaml
#panel_iframe: !include iframe.yaml
#recorder: !include recorder.yaml
#scene: !include scenes.yaml
#shell_command: !include shell_command.yaml
#timer: !include timers.yaml
#zone: !include_dir_list zones/

