#### lights.yaml ####
- platform: yeelight
  devices:
    192.168.1.6:
      name: corner_lamp
      transition: 1000
      use_music_mode: True #(defaults to False)
      save_on_change: False #(defaults to True)
