#### Switches.yaml ####
- platform: broadlink
  host: !secret sonoff_rm_pro_IP
  mac: !secret sonoff_rm_pro_MAC
  timeout: 15
  switches:
  # Will work on most Phillips TVs:
    tv_power:
      friendly_name: "Samsung Tv Power"
      command_on: 'JgDSAJWUEzcTNxM2ExITEhQSExITEhM3EzYUNhMSExIUEhMSExITEhM3ExITEhMSExITEhMSEzcTEhM3EzcTNxM2EzcTNxMABf+VlBM3EzcTNxMSExITEhMSExITNxM3EzcTEhMSExITEhMSExITNxMSExITEhMSFBITEhM2FBITNhM3EzcTNxM3EzYTAAYAlZQTNxM2FDYTEhMSFBITEhMSEzcTNhM3ExITEhMSFBITEhMSEzcTEhMSExITEhMSExITNxMSEzcTNxM2EzcTNxM3EwANBQAAAAAAAA=='
      command_off: 'JgDSAJWUEzcTNxM2ExITEhQSExITEhM3EzYUNhMSExIUEhMSExITEhM3ExITEhMSExITEhMSEzcTEhM3EzcTNxM2EzcTNxMABf+VlBM3EzcTNxMSExITEhMSExITNxM3EzcTEhMSExITEhMSExITNxMSExITEhMSFBITEhM2FBITNhM3EzcTNxM3EzYTAAYAlZQTNxM2FDYTEhMSFBITEhMSEzcTNhM3ExITEhMSFBITEhMSEzcTEhMSExITEhMSExITNxMSEzcTNxM2EzcTNxM3EwANBQAAAAAAAA=='
    tv_source:
      friendly_name: "Samsung Source"
      command_on: 'JgAoAAQAB3IEAAVRBQAEywWCBAAEPwWEBQAGYwUABmIHAAQ9BQALtwUADQU='
      command_off: 'JgAoAAQAB3IEAAVRBQAEywWCBAAEPwWEBQAGYwUABmIHAAQ9BQALtwUADQU='
    ac_cold:
      friendly_name: "AC Cold"
      command_on: 'JgCyAGSCPyEfQT4hHiEfIh4gICAfIh5APyAgQD8iHiAfIR8hHyAfIR8gHyEfIR8gHyIeQT4hHyEeIR9BPyFggj8gH0I9IR8iHiAfIR8iHiEeQj4hHkE/IR4hHyEfIB8hICAfIB8hHyAfIR8hH0E+IR8hHiEfQD8hYIM+IR9APyEfIR8gHyIgHx4iHkA/Ih5BPiIeIB8hHyIeICAhHiIeIB8hHyEfIB9BPyEeIR8hHkE/IIEADQUAAAAAAAA='
      command_off: 'JgCyAGSCPyEfQT4hHiEfIh4gICAfIh5APyAgQD8iHiAfIR8hHyAfIR8gHyEfIR8gHyIeQT4hHyEeIR9BPyFggj8gH0I9IR8iHiAfIR8iHiEeQj4hHkE/IR4hHyEfIB8hICAfIB8hHyAfIR8hH0E+IR8hHiEfQD8hYIM+IR9APyEfIR8gHyIgHx4iHkA/Ih5BPiIeIB8hHyIeICAhHiIeIB8hHyEfIB9BPyEeIR8hHkE/IIEADQUAAAAAAAA='
    ac_hot:
      friendly_name: "AC Hot"
      command_on: 'JgCyAGSCPyEfQT4hHiEfIh4gICAfIh5APyAgQD8iHiAfIR8hHyAfIR8gHyEfIR8gHyIeQT4hHyEeIR9BPyFggj8gH0I9IR8iHiAfIR8iHiEeQj4hHkE/IR4hHyEfIB8hICAfIB8hHyAfIR8hH0E+IR8hHiEfQD8hYIM+IR9APyEfIR8gHyIgHx4iHkA/Ih5BPiIeIB8hHyIeICAhHiIeIB8hHyEfIB9BPyEeIR8hHkE/IIEADQUAAAAAAAA='
      command_off: 'JgCyAGSCPyEfQT4hHiEfIh4gICAfIh5APyAgQD8iHiAfIR8hHyAfIR8gHyEfIR8gHyIeQT4hHyEeIR9BPyFggj8gH0I9IR8iHiAfIR8iHiEeQj4hHkE/IR4hHyEfIB8hICAfIB8hHyAfIR8hH0E+IR8hHiEfQD8hYIM+IR9APyEfIR8gHyIgHx4iHkA/Ih5BPiIeIB8hHyIeICAhHiIeIB8hHyEfIB9BPyEeIR8hHkE/IIEADQUAAAAAAAA='
    ac_fan:
      friendly_name: "AC Fan"
      command_on: 'JgCyAGSCPyEfQT4hHiEfIh4gICAfIh5APyAgQD8iHiAfIR8hHyAfIR8gHyEfIR8gHyIeQT4hHyEeIR9BPyFggj8gH0I9IR8iHiAfIR8iHiEeQj4hHkE/IR4hHyEfIB8hICAfIB8hHyAfIR8hH0E+IR8hHiEfQD8hYIM+IR9APyEfIR8gHyIgHx4iHkA/Ih5BPiIeIB8hHyIeICAhHiIeIB8hHyEfIB9BPyEeIR8hHkE/IIEADQUAAAAAAAA='
      command_off: 'JgCyAGSCPyEfQT4hHiEfIh4gICAfIh5APyAgQD8iHiAfIR8hHyAfIR8gHyEfIR8gHyIeQT4hHyEeIR9BPyFggj8gH0I9IR8iHiAfIR8iHiEeQj4hHkE/IR4hHyEfIB8hICAfIB8hHyAfIR8hH0E+IR8hHiEfQD8hYIM+IR9APyEfIR8gHyIgHx4iHkA/Ih5BPiIeIB8hHyIeICAhHiIeIB8hHyEfIB9BPyEeIR8hHkE/IIEADQUAAAAAAAA='
    audio:
      friendly_name: "Yamaha IR"
      command_on: 'JgBgAAABKJIUERQ2FDUVNRU1FTUUNhQRFDYUERQRFBEUERQRFBEUNhQRFDYUERQ2FBEUNhQRFBEUNhQRFDUVEBU1FRAVNRQ2FAAFFgABKEgVAAxOAAEoSBUADE4AAShIFAANBQAAAAAAAAAA'
      command_off: 'JgBgAAABKJIUERQ2FDUVNRU1FTUUNhQRFDYUERQRFBEUERQRFBEUNhQRFDYUERQ2FBEUNhQRFBEUNhQRFDUVEBU1FRAVNRQ2FAAFFgABKEgVAAxOAAEoSBUADE4AAShIFAANBQAAAAAAAAAA'


- platform: broadlink
  host: !secret sonoff_rm_basic_IP
  mac: !secret sonoff_rm_basic_IP
  timeout: 15
  switches:
    ac_fan2:
      friendly_name: "AC Fan Basic"
      command_on: 'JgCyAGSCPyEfQT4hHiEfIh4gICAfIh5APyAgQD8iHiAfIR8hHyAfIR8gHyEfIR8gHyIeQT4hHyEeIR9BPyFggj8gH0I9IR8iHiAfIR8iHiEeQj4hHkE/IR4hHyEfIB8hICAfIB8hHyAfIR8hH0E+IR8hHiEfQD8hYIM+IR9APyEfIR8gHyIgHx4iHkA/Ih5BPiIeIB8hHyIeICAhHiIeIB8hHyEfIB9BPyEeIR8hHkE/IIEADQUAAAAAAAA='
      command_off: 'JgCyAGSCPyEfQT4hHiEfIh4gICAfIh5APyAgQD8iHiAfIR8hHyAfIR8gHyEfIR8gHyIeQT4hHyEeIR9BPyFggj8gH0I9IR8iHiAfIR8iHiEeQj4hHkE/IR4hHyEfIB8hICAfIB8hHyAfIR8hH0E+IR8hHiEfQD8hYIM+IR9APyEfIR8gHyIgHx4iHkA/Ih5BPiIeIB8hHyIeICAhHiIeIB8hHyEfIB9BPyEeIR8hHkE/IIEADQUAAAAAAAA='
     
     
- platform: mqtt
  name: "Kitchen"
  state_topic: "home/sonoff/living_room/1/stat"
  command_topic: "home/sonoff/living_room/1"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "SoNOFF2"
  state_topic: "home/sonoff/living_room/2/stat"
  command_topic: "home/sonoff/living_room/2"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "SoNOFF3"
  state_topic: "home/sonoff/living_room/3/stat"
  command_topic: "home/sonoff/living_room/3"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "SoNOFF4"
  state_topic: "home/sonoff/living_room/4/stat"
  command_topic: "home/sonoff/living_room/4"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true
