#### Switches.yaml ####
- platform: broadlink
  host: !secret sonoff_rm_pro_IP
  mac: !secret sonoff_rm_pro_MAC
  timeout: 15
  switches:
  # Will work on most Phillips TVs:
    tv_power:
      friendly_name: "Samsung Tv Power"
      command_on: 'JgDSAJWUEzcTNxM2ExITEhQSExITEhM3EzYUNhMSExIUEhMSExITEhM3ExITEhMSExITEhMSEzcTEhM3EzcTNxM2EzcTNxMABf+VlBM3EzcTNxMSExITEhMSExITNxM3EzcTEhMSExITEhMSExITNxMSExITEhMSFBITEhM2FBITNhM3EzcTNxM3EzYTAAYAlZQTNxM2FDYTEhMSFBITEhMSEzcTNhM3ExITEhMSFBITEhMSEzcTEhMSExITEhMSExITNxMSEzcTNxM2EzcTNxM3EwANBQAAAAAAAA=='
      command_off: 'JgDSAJWUEzcTNxM2ExITEhQSExITEhM3EzYUNhMSExIUEhMSExITEhM3ExITEhMSExITEhMSEzcTEhM3EzcTNxM2EzcTNxMABf+VlBM3EzcTNxMSExITEhMSExITNxM3EzcTEhMSExITEhMSExITNxMSExITEhMSFBITEhM2FBITNhM3EzcTNxM3EzYTAAYAlZQTNxM2FDYTEhMSFBITEhMSEzcTNhM3ExITEhMSFBITEhMSEzcTEhMSExITEhMSExITNxMSEzcTNxM2EzcTNxM3EwANBQAAAAAAAA=='
    tv_source:
      friendly_name: "Samsung Source"
      command_on: 'JgAoAAQAB3IEAAVRBQAEywWCBAAEPwWEBQAGYwUABmIHAAQ9BQALtwUADQU='
      command_off: 'JgAoAAQAB3IEAAVRBQAEywWCBAAEPwWEBQAGYwUABmIHAAQ9BQALtwUADQU='
      
    aircon_power:
      friendly_name: "AC"
      command_on: 'JgC+AGV/PyEgP0EfHiEhIB4hIB8hICE9QSAdIR8hISAdISEgICAdIR8hICAgICAgHSEhICAgIB8eISEfHiEiPkAgYYFAHyE/QR4hICAfHiEhIB8gHkBBICAgHSEfIR4iICAgIB0hISAeIR4hHyEeIR8hISAdISEgICAfHx9BQR5jgT0hH0FBHiEgHSEhICAgIB8eQUEeISAdIiEfICAgHyEeISAgHyAgHSEfIR8hIR8eISEgIB8hHiAfH0FBH4IADQUAAAAAAAAAAAAA='
      command_off: 'JgC+AGV/PyEgP0EfHiEhIB4hIB8hICE9QSAdIR8hISAdISEgICAdIR8hICAgICAgHSEhICAgIB8eISEfHiEiPkAgYYFAHyE/QR4hICAfHiEhIB8gHkBBICAgHSEfIR4iICAgIB0hISAeIR4hHyEeIR8hISAdISEgICAfHx9BQR5jgT0hH0FBHiEgHSEhICAgIB8eQUEeISAdIiEfICAgHyEeISAgHyAgHSEfIR8hIR8eISEgIB8hHiAfH0FBH4IADQUAAAAAAAAAAAAA='
    aircon_fan:
      friendly_name: "AC Fan"
      command_on: 'JgC+AGV/PyEgP0EfHiEhIB4hIB8hICE9QSAdIR8hISAdISEgICAdIR8hICAgICAgHSEhICAgIB8eISEfHiEiPkAgYYFAHyE/JgCyAGSAIh5CPUAgHiEfISIeIR8gICA+QCAhHyEeICAhHiEfICAhHiIeIR8hHh8hIh0hHyA/Qh4eQUI9QR9jgR8fQEA+IR8hICAeISEgIB8gQD8gICAfIB4hICAgHyEfHyEhHyAfICAeISEfIB8hPz4hIUBAP0AgYYEeIT5BQSAgHh8hISAgHyAgHUE/ISAfHyEhICAfICAgIB8gICAfHx8hICAgHyEfH0BBIB1BP0E+IYIADQUAAAAAAAA=='
      command_off: 'JgC+AGV/PyEgP0EfHiEhIB4hIB8hICE9QSAdIR8hISAdISEgICAdIR8hICAgICAgHSEhICAgIB8eISEfHiEiPkAgYYFAHyE/JgCyAGSAIh5CPUAgHiEfISIeIR8gICA+QCAhHyEeICAhHiEfICAhHiIeIR8hHh8hIh0hHyA/Qh4eQUI9QR9jgR8fQEA+IR8hICAeISEgIB8gQD8gICAfIB4hICAgHyEfHyEhHyAfICAeISEfIB8hPz4hIUBAP0AgYYEeIT5BQSAgHh8hISAgHyAgHUE/ISAfHyEhICAfICAgIB8gICAfHx8hICAgHyEfH0BBIB1BP0E+IYIADQUAAAAAAAA='
     
    audio:
      friendly_name: "Yamaha IR"
      command_on: 'JgBgAAABKJIUERQ2FDUVNRU1FTUUNhQRFDYUERQRFBEUERQRFBEUNhQRFDYUERQ2FBEUNhQRFBEUNhQRFDUVEBU1FRAVNRQ2FAAFFgABKEgVAAxOAAEoSBUADE4AAShIFAANBQAAAAAAAAAA'
      command_off: 'JgBgAAABKJIUERQ2FDUVNRU1FTUUNhQRFDYUERQRFBEUERQRFBEUNhQRFDYUERQ2FBEUNhQRFBEUNhQRFDUVEBU1FRAVNRQ2FAAFFgABKEgVAAxOAAEoSBUADE4AAShIFAANBQAAAAAAAAAA'

     
- platform: mqtt
  name: "Kitchen"
  state_topic: "home/sonoff/living_room/1/stat"
  command_topic: "home/sonoff/living_room/1"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "SoNOFF2"
  state_topic: "home/sonoff/living_room/2/stat"
  command_topic: "home/sonoff/living_room/2"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "SoNOFF3"
  state_topic: "home/sonoff/living_room/3/stat"
  command_topic: "home/sonoff/living_room/3"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "SoNOFF4"
  state_topic: "home/sonoff/living_room/4/stat"
  command_topic: "home/sonoff/living_room/4"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true
