#### Switches.yaml ####
- platform: broadlink
  host: !secret sonoff_rm_basic_IP
  mac: !secret sonoff_rm_basic_MAC
  timeout: 15
  switches:
  # Will work on most Phillips TVs:
    tv:
      friendly_name: "Samsung Tv"
      command_on: 'JgDSAJWUEzcTNxM2ExITEhQSExITEhM3EzYUNhMSExIUEhMSExITEhM3ExITEhMSExITEhMSEzcTEhM3EzcTNxM2EzcTNxMABf+VlBM3EzcTNxMSExITEhMSExITNxM3EzcTEhMSExITEhMSExITNxMSExITEhMSFBITEhM2FBITNhM3EzcTNxM3EzYTAAYAlZQTNxM2FDYTEhMSFBITEhMSEzcTNhM3ExITEhMSFBITEhMSEzcTEhMSExITEhMSExITNxMSEzcTNxM2EzcTNxM3EwANBQAAAAAAAA=='
      command_off: 'JgDSAJWUEzcTNxM2ExITEhQSExITEhM3EzYUNhMSExIUEhMSExITEhM3ExITEhMSExITEhMSEzcTEhM3EzcTNxM2EzcTNxMABf+VlBM3EzcTNxMSExITEhMSExITNxM3EzcTEhMSExITEhMSExITNxMSExITEhMSFBITEhM2FBITNhM3EzcTNxM3EzYTAAYAlZQTNxM2FDYTEhMSFBITEhMSEzcTNhM3ExITEhMSFBITEhMSEzcTEhMSExITEhMSExITNxMSEzcTNxM2EzcTNxM3EwANBQAAAAAAAA=='

    aircon:
      friendly_name: "Electra aircon"
      command_on: 'JgC+AGV/PyEgP0EfHiEhIB4hIB8hICE9QSAdIR8hISAdISEgICAdIR8hICAgICAgHSEhICAgIB8eISEfHiEiPkAgYYFAHyE/QR4hICAfHiEhIB8gHkBBICAgHSEfIR4iICAgIB0hISAeIR4hHyEeIR8hISAdISEgICAfHx9BQR5jgT0hH0FBHiEgHSEhICAgIB8eQUEeISAdIiEfICAgHyEeISAgHyAgHSEfIR8hIR8eISEgIB8hHiAfH0FBH4IADQUAAAAAAAAAAAAA='
      command_off: 'JgC+AGV/PyEgP0EfHiEhIB4hIB8hICE9QSAdIR8hISAdISEgICAdIR8hICAgICAgHSEhICAgIB8eISEfHiEiPkAgYYFAHyE/QR4hICAfHiEhIB8gHkBBICAgHSEfIR4iICAgIB0hISAeIR4hHyEeIR8hISAdISEgICAfHx9BQR5jgT0hH0FBHiEgHSEhICAgIB8eQUEeISAdIiEfICAgHyEeISAgHyAgHSEfIR8hIR8eISEgIB8hHiAfH0FBH4IADQUAAAAAAAAAAAAA='

    audio:
      friendly_name: "Yamaha"
      command_on: 'JgBgAAABKJIUERQ2FDUVNRU1FTUUNhQRFDYUERQRFBEUERQRFBEUNhQRFDYUERQ2FBEUNhQRFBEUNhQRFDUVEBU1FRAVNRQ2FAAFFgABKEgVAAxOAAEoSBUADE4AAShIFAANBQAAAAAAAAAA'
      command_off: 'JgBgAAABKJIUERQ2FDUVNRU1FTUUNhQRFDYUERQRFBEUERQRFBEUNhQRFDYUERQ2FBEUNhQRFBEUNhQRFDUVEBU1FRAVNRQ2FAAFFgABKEgVAAxOAAEoSBUADE4AAShIFAANBQAAAAAAAAAA'


- platform: mqtt
  name: "SoNOFF"
  state_topic: "home/sonoff/living_room/1/stat"
  command_topic: "home/sonoff/living_room/1"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true
