#### input_select.yaml ####
lr_ac_fan:
  name: lr_ac_fan
  options:
   - LOW
   - MED
   - HIGH
   - AUTO
lr_ac_mode:
  name: lr_ac_mode
  options:
   - COOL
   - HEAT
   - FAN

radio_station:
  name: 'Select Radio Station:'
  options:
    - GalGalatz
    - Galatz
    - Radius 100FM
    - Echo 99FM
    - Kan 88FM
    - 103FM
    - Lev Hamedina 91FM
    - Reshet Gimel
    - Radio Darom
    - Kol Hayam Haadom 102FM
  icon: mdi:radio
chromecast_radio:
  name: 'Select Speakers:'
  options:
    - Livingroom
    - Everywhere
  initial: Everywhere
  icon: mdi:speaker-wireless