#### lights.yaml ####
- platform: yeelight
  devices:
    192.168.1.50:
      name: yeelight3
      transition: 1000
      use_music_mode: True #(defaults to False)
      save_on_change: False #(defaults to True)
    192.168.1.51:
      name: hall_light
      transition: 1000
      use_music_mode: True #(defaults to False)
      save_on_change: False #(defaults to True)
    192.168.1.52:
      name: corner_light
      transition: 1000
      use_music_mode: True #(defaults to False)
      save_on_change: False #(defaults to True)
    192.168.1.53:
      name: hall_light2
      transition: 1000
      use_music_mode: True #(defaults to False)
      save_on_change: False #(defaults to True)