#### Sensors.yaml ####
- platform: broadlink
  host: !secret sonoff_rm_pro_IP
  mac: !secret sonoff_rm_pro_MAC
  friendly_name: 'Pro'
  monitored_conditions:
    - 'temperature'

#### TIME/DATE ##################################
- platform: time_date
  display_options:
      - 'time'
      - 'date'
- platform: worldclock
  time_zone: Etc/UTC
  name: 'UTC'
- platform: worldclock
  time_zone: America/New_York
  name: 'Ann Arbor'

- platform: speedtest
  minute: 59
  monitored_conditions:
    - ping
    - download
    - upload
# Friendly Date

# - platform: template
#   sensors:
#     friendly_date:
#       # Thursday June 10th, 2017
#       friendly_name: "Today's Date"
#       value_template: "{{ now().strftime('%A %B %e, %Y') }}"
#     friendly_date_day:
#       # Thu
#       friendly_name: "Today's Day"
#       value_template: "{{ now().strftime('%a') }}"

# For Alarm Clock
#- platform: template
#  sensors:
#    alarm_time:
#      friendly_name: 'Time'
#      value_template: '{{ "%0.02d:%0.02d" | format(states("input_slider.alarmhour") | int, states("input_slider.alarmminutes") | int) }}'

- platform: template
  sensors:
    lr_ac_temp_sensor:
      value_template: "{{ states.input_text.lr_ac_temp_text.state }}"