#### Switches.yaml ####
- platform: broadlink
  host: !secret sonoff_rm_pro_IP
  mac: !secret sonoff_rm_pro_MAC
  timeout: 15
  switches:
  # Will work on most Phillips TVs:
    tv_power:
      friendly_name: "Samsung Tv Power"
      command_on: 'JgDSAJWUEzcTNxM2ExITEhQSExITEhM3EzYUNhMSExIUEhMSExITEhM3ExITEhMSExITEhMSEzcTEhM3EzcTNxM2EzcTNxMABf+VlBM3EzcTNxMSExITEhMSExITNxM3EzcTEhMSExITEhMSExITNxMSExITEhMSFBITEhM2FBITNhM3EzcTNxM3EzYTAAYAlZQTNxM2FDYTEhMSFBITEhMSEzcTNhM3ExITEhMSFBITEhMSEzcTEhMSExITEhMSExITNxMSEzcTNxM2EzcTNxM3EwANBQAAAAAAAA=='
      command_off: 'JgDSAJWUEzcTNxM2ExITEhQSExITEhM3EzYUNhMSExIUEhMSExITEhM3ExITEhMSExITEhMSEzcTEhM3EzcTNxM2EzcTNxMABf+VlBM3EzcTNxMSExITEhMSExITNxM3EzcTEhMSExITEhMSExITNxMSExITEhMSFBITEhM2FBITNhM3EzcTNxM3EzYTAAYAlZQTNxM2FDYTEhMSFBITEhMSEzcTNhM3ExITEhMSFBITEhMSEzcTEhMSExITEhMSExITNxMSEzcTNxM2EzcTNxM3EwANBQAAAAAAAA=='
    tv_source:
      friendly_name: "Samsung Source"
      command_on: 'JgAoAAQAB3IEAAVRBQAEywWCBAAEPwWEBQAGYwUABmIHAAQ9BQALtwUADQU='
      command_off: 'JgAoAAQAB3IEAAVRBQAEywWCBAAEPwWEBQAGYwUABmIHAAQ9BQALtwUADQU='
    ac_cold:
      friendly_name: "AC Cold"
      command_on: 'JgC4AGeAQB4hPz8gIh8gIB8fIR8hHyE/QR8gP0AfIB8hHx8gHyEhHyEfIB8hHyEeIR8hHyEeIR8hPiEfIh8/H2OBQB8gP0EeHyEfISEeIh8hHyA/QR4gP0EfIR8hHyAfIB8fISEfHiEhHyEeIh8hHx8fIh8gPyAfIh9AH2KAQR8gPz8gIR8hHyEfIB8hHyA/QR8fQEEfIR8gHyEfIR8gHyEgHx8hHyEfIR8gHyEfIR8gPiIfIB9BH4EADQU='
      command_off: 'JgC4AGeAQB4hPz8gIh8gIB8fIR8hHyE/QR8gP0AfIB8hHx8gHyEhHyEfIB8hHyEeIR8hHyEeIR8hPiEfIh8/H2OBQB8gP0EeHyEfISEeIh8hHyA/QR4gP0EfIR8hHyAfIB8fISEfHiEhHyEeIh8hHx8fIh8gPyAfIh9AH2KAQR8gPz8gIR8hHyEfIB8hHyA/QR8fQEEfIR8gHyEfIR8gHyEgHx8hHyEfIR8gHyEfIR8gPiIfIB9BH4EADQU='    
    ac_hot:
      friendly_name: "AC Hot"
      command_on: 'JgC+AGSBPz9BHyEfHiEhHx4hHyEfICE/PyAfISEfIR8gHyEfIB8iHyAeIh8hHyAfIB8hICAfIB8hHyE+IR8fIEIfYoFAPz4gIh8gHyEeIR8hHh8hIT9AHyEfHyAhHx8hIR8gHyEfIB8fIR8gIR8fIR8hIR8gHyEfID8hHyAfQSBhgEI/QB8hHyAfIB8hHyAfIR8hPkIfICAeICIfHiAfISIfHx8fIR8hHyAfIR8hHyAfIR8hIR8eQR8gHyE/IYAADQUAAAAAAAAAAAAA'
      command_off: 'JgC+AGSBPz9BHyEfHiEhHx4hHyEfICE/PyAfISEfIR8gHyEfIB8iHyAeIh8hHyAfIB8hICAfIB8hHyE+IR8fIEIfYoFAPz4gIh8gHyEeIR8hHh8hIT9AHyEfHyAhHx8hIR8gHyEfIB8fIR8gIR8fIR8hIR8gHyEfID8hHyAfQSBhgEI/QB8hHyAfIB8hHyAfIR8hPkIfICAeICIfHiAfISIfHx8fIR8hHyAfIR8hHyAfIR8hIR8eQR8gHyE/IYAADQUAAAAAAAAAAAAA'
    ac_fan:
      friendly_name: "AC Fan"
      command_on: 'JgC4AGZ/Ih5CPUEhIB0hICEeIR4iHiI9Qh4hQEAeIh0iHiEgIR4hHiEgIB4iHiIdIh4iHiEfIR8gICA/IR9BHmKBIR5BPkIeICEfICAfIR8hHiE/QCAgPkIeIR8gICAgIB8gICEeIR8gICEeIR8gICAfIR4hICA9Ix5BH2J/Ih9BPUEhIB4hHyAhIB4hHyE9Qh8hPUEhHyAgHyEfICAhHiEfIR4hICAeIh0iHiIeIR8gICE9Ih9BHoMADQU='
      command_off: 'JgC4AGZ/Ih5CPUEhIB0hICEeIR4iHiI9Qh4hQEAeIh0iHiEgIR4hHiEgIB4iHiIdIh4iHiEfIR8gICA/IR9BHmKBIR5BPkIeICEfICAfIR8hHiE/QCAgPkIeIR8gICAgIB8gICEeIR8gICEeIR8gICAfIR4hICA9Ix5BH2J/Ih9BPUEhIB4hHyAhIB4hHyE9Qh8hPUEhHyAgHyEfICAhHiEfIR4hICAeIh0iHiIeIR8gICE9Ih9BHoMADQU='
    audio:
      friendly_name: "Yamaha IR"
      command_on: 'JgBgAAABKJIUERQ2FDUVNRU1FTUUNhQRFDYUERQRFBEUERQRFBEUNhQRFDYUERQ2FBEUNhQRFBEUNhQRFDUVEBU1FRAVNRQ2FAAFFgABKEgVAAxOAAEoSBUADE4AAShIFAANBQAAAAAAAAAA'
      command_off: 'JgBgAAABKJIUERQ2FDUVNRU1FTUUNhQRFDYUERQRFBEUERQRFBEUNhQRFDYUERQ2FBEUNhQRFBEUNhQRFDUVEBU1FRAVNRQ2FAAFFgABKEgVAAxOAAEoSBUADE4AAShIFAANBQAAAAAAAAAA'
    living_room_light_left:
      friendly_name: "Salon light left"
      command_on: 'sgY0AAwhIwsMIgwhIwwjCyMLDSEMIgwhIwsMIQwhDAABVCMLIgsjCyMLIwsjCwwhIwsMISMLIwsAAAAA'
      command_off: 'sgY0AAwhIwsMIgwhIwwjCyMLDSEMIgwhIwsMIQwhDAABVCMLIgsjCyMLIwsjCwwhIwsMISMLIwsAAAAA'
    living_room_light_right:
      friendly_name: "Salon light right"
      command_on: 'sgY0AAwhIwsMIgwhIwwjCyMLDSEMIgwhIwsMIQwhDAABVCMLIgsjCyMLIwsjCwwhIwsMISMLIwsAAAAA'
      command_off: 'sgY0AAwhIwsMIgwhIwwjCyMLDSEMIgwhIwsMIQwhDAABVCMLIgsjCyMLIwsjCwwhIwsMISMLIwsAAAAA'

- platform: broadlink
  host: !secret sonoff_rm_basic_IP
  mac: !secret sonoff_rm_basic_IP
  timeout: 15
  switches:
    ac_fan2:
      friendly_name: "AC Fan Basic"
      command_on: 'JgCyAGSCPyEfQT4hHiEfIh4gICAfIh5APyAgQD8iHiAfIR8hHyAfIR8gHyEfIR8gHyIeQT4hHyEeIR9BPyFggj8gH0I9IR8iHiAfIR8iHiEeQj4hHkE/IR4hHyEfIB8hICAfIB8hHyAfIR8hH0E+IR8hHiEfQD8hYIM+IR9APyEfIR8gHyIgHx4iHkA/Ih5BPiIeIB8hHyIeICAhHiIeIB8hHyEfIB9BPyEeIR8hHkE/IIEADQUAAAAAAAA='
      command_off: 'JgCyAGSCPyEfQT4hHiEfIh4gICAfIh5APyAgQD8iHiAfIR8hHyAfIR8gHyEfIR8gHyIeQT4hHyEeIR9BPyFggj8gH0I9IR8iHiAfIR8iHiEeQj4hHkE/IR4hHyEfIB8hICAfIB8hHyAfIR8hH0E+IR8hHiEfQD8hYIM+IR9APyEfIR8gHyIgHx4iHkA/Ih5BPiIeIB8hHyIeICAhHiIeIB8hHyEfIB9BPyEeIR8hHkE/IIEADQUAAAAAAAA='
     
     
- platform: mqtt
  name: "Kitchen"
  state_topic: "home/sonoff/living_room/1/stat"
  command_topic: "home/sonoff/living_room/1"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "SoNOFF2"
  state_topic: "home/sonoff/living_room/2/stat"
  command_topic: "home/sonoff/living_room/2"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "SoNOFF3"
  state_topic: "home/sonoff/living_room/3/stat"
  command_topic: "home/sonoff/living_room/3"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "SoNOFF4"
  state_topic: "home/sonoff/living_room/4/stat"
  command_topic: "home/sonoff/living_room/4"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true
